export const fetchCourses = {
    FETCH_COURSES: "FETCH_COURSES",
    FETCH_COURSES_PENDING: "FETCH_COURSES_PENDING",
    FETCH_COURSES_FULFILLED: "FETCH_COURSES_FULFILLED",
    FETCH_COURSES_REJECTED: "FETCH_COURSES_REJECTED",
}

export const postCourse = {
    POST_COURSE: "POST_COURSE",
    POST_COURSE_PENDING: "POST_COURSE_PENDING",
    POST_COURSE_FULFILLED: "POST_COURSE_FULFILLED",
    POST_COURSE_REJECTED: "POST_COURSE_REJECTED",
}

export const deleteCourse = {
    DELETE_COURSE: "DELETE_COURSE",
    DELETE_COURSE_PENDING: "DELETE_COURSE_PENDING",
    DELETE_COURSE_FULFILLED: "DELETE_COURSE_FULFILLED",
    DELETE_COURSE_REJECTED: "DELETE_COURSE_REJECTED",
}

export const getCourse = {
    GET_COURSE: "GET_COURSE",
    GET_COURSE_PENDING: "GET_COURSE_PENDING",
    GET_COURSE_FULFILLED: "GET_COURSE_FULFILLED",
    GET_COURSE_REJECTED: "GET_COURSE_REJECTED",
}

export const editCourse = {
    EDIT_COURSE: "EDIT_COURSE",
    EDIT_COURSE_PENDING: "EDIT_COURSE_PENDING",
    EDIT_COURSE_FULFILLED: "EDIT_COURSE_FULFILLED",
    EDIT_COURSE_REJECTED: "EDIT_COURSE_REJECTED",
}